version: "3.7"
services:
 db:
    image: mysql:5.7
    container_name: diancagoods-db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/docker-entrypoint-initdb.d
    networks:
      - diancagoods
 app:
    build:
      args:
        user: diancagoods
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: diancagoods
    restart: unless-stopped
    container_name: diancagoods-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - diancagoods
 nginx:
    image: nginx:1.17-alpine
    container_name: diancagoods-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - diancagoods

networks:
  diancagoods:
    driver: bridge

composer_installation:
  container_name: composer_installation
  image: composer
  volumes:
    - ./:/app
  command: composer install --ignore-platform-reqs